In [4]:
import tensorflow as tf

graph1 = tf.Graph()

with graph1.as_default():
    a = tf.constant([2], name = 'constant_a')
    b = tf.constant([3], name = 'constant_b')
    
a

# Printing the value of a
sess = tf.Session(graph = graph1)
result = sess.run(a)
print(result)
sess.close()



[2]


In [0]:
with graph1.as_default():
    c = tf.add(a, b)
    #c = a + b is also a way to define the sum of the terms

In [0]:
sess = tf.Session(graph = graph1)

In [0]:
#run session in with block to end session automatically instead of sess.close()
with tf.Session(graph = graph1) as sess:
    result = sess.run(c)
    print(result)


In [8]:
#layout of different dimensions

graph2 = tf.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,2])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = sess.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = sess.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [9]:
#operations applied to matrices
#shows that tf function and math operator produces same result
graph3 = tf.Graph()
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

    add_1_operation = tf.add(Matrix_one, Matrix_two)
    add_2_operation = Matrix_one + Matrix_two

with tf.Session(graph =graph3) as sess:
    result = sess.run(add_1_operation)
    print ("Defined using tensorflow function :")
    print(result)
    result = sess.run(add_2_operation)
    print ("Defined using normal expressions :")
    print(result)

Defined using tensorflow function :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions :
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [10]:
#matrix multiplication with tf.matmul
graph4 = tf.Graph()
with graph4.as_default():
    Matrix_one = tf.constant([[2,3],[3,4]])
    Matrix_two = tf.constant([[2,3],[3,4]])

    mul_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session(graph = graph4) as sess:
    result = sess.run(mul_operation)
    print ("Defined using tensorflow function :")
    print(result)

Defined using tensorflow function :
[[13 18]
 [18 25]]


In [11]:
#Using Variables

v = tf.Variable(0)
update = tf.assign(v, v+1)
#Variables must be initialized by running an initialization operation after having launched the graph
init_op = tf.global_variables_initializer()
#start session
with tf.Session() as session:
  #run initialization
    session.run(init_op)
    #print before value
    print(session.run(v))
    #update value and print updated value
    for _ in range(3):
        session.run(update)
        print(session.run(v))

0
1
2
3


In [12]:
#using Placeholders
#Placeholders can be seen as "holes" in your model, "holes" which you will pass the data to, you can create them using tf.placeholder(datatype)

a = tf.placeholder(tf.float32)
b = a * 2
#To pass the data into the model we call the session with 
#an extra argument feed_dict in which we should pass a dictionary with each placeholder name followed by its respective data
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print (result)
#Since data in TensorFlow is passed in form of multidimensional arrays we can pass any kind of tensor
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

7.0
[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [13]:
#Operations
#Operations are nodes that represent the mathematical operations over the tensors on a graph. 
#These operations can be any kind of functions, like add and subtract tensor or maybe an activation function.
#tf.constant, tf.matmul, tf.add, tf.nn.sigmoid are some of the operations in TensorFlow. 
#These are like functions in python but operate directly over tensors and each one does a specific thing.
#Other operations can be easily found in: https://www.tensorflow.org/versions/r0.9/api_docs/python/index.html

graph5 = tf.Graph()
with graph5.as_default():
    a = tf.constant([5])
    b = tf.constant([2])
    c = tf.add(a,b)
    d = tf.subtract(a,b)

with tf.Session(graph = graph5) as sess:
    result = sess.run(c)
    print ('c =: %s' % result)
    result = sess.run(d)
    print ('d =: %s' % result)

c =: [7]
d =: [3]
